apps/nectar/web/router.ex
defmodule Nectar.Router do
  use Nectar.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :admin_browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Nectar.Plugs.AdminAccessRequired
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/", Nectar do

    pipe_through [:browser, :browser_auth] # Use the default browser stack

    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create]
    delete "/logout", SessionController, :logout

    resources "/orders", OrderController, only: [:index, :show]

  end

  # all actions where the user's cart is required go here.
  # note: if cart is not present it will create and link a new one.
  scope "/", Nectar do
    pipe_through [:browser, :browser_auth, Nectar.Plugs.Cart]
    get "/", ProductController, :index, as: :home

    get "/cart", CartController, :show
    put "/cart", CartController, :update

    resources "/products", ProductController, only: [:show, :index]
    resources "/line_items", LineItemController, only: [:create, :delete]
    get "/checkout",      CheckoutController, :checkout
    put "/checkout/next", CheckoutController, :next
    put "/checkout/back", CheckoutController, :back
    resources "/categories", CategoryController do
      get "/products", CategoryController, :associated_products, as: :products
    end
  end

  scope "/admin", Nectar.Admin, as: :admin do
    pipe_through [:browser, :admin_browser_auth]

    get "/", HomeController, :index
    resources "/countries", CountryController do
      resources "/states", StateController, only: [:create, :delete]
    end
    resources "/zones", ZoneController do
      resources "/members", ZoneMemberController, only: [:create, :delete]
    end

    resources "/cart", CartController, only: [:new, :edit, :create]

    resources "/categories", CategoryController

    resources "/orders", OrderController, only: [:index, :show, :update, :edit] do
      resources "/line_items", LineItemController, only: [:create, :delete] do
        put "/update_fullfillment", LineItemController, :update_fullfillment
      end
      get "/checkout", CheckoutController, :checkout
      put "/checkout/next", CheckoutController, :next
      put "/checkout/back", CheckoutController, :back
      resources "/payments", PaymentController, only: [:show] do
        put "/refund",  PaymentController, :refund,  as: :refund
        put "/capture", PaymentController, :capture, as: :capture
      end
    end

    resources "/users", UserController do
      get "/all_pending_orders", UserController, :all_pending_orders
    end

    resources "/settings", SettingController, only: [:edit, :update]
    get "/settings/payment", SettingController,  :payment_method_settings
    get "/settings/shipping", SettingController, :shipping_method_settings
    post "/settings/payment", SettingController,  :update_payment_method_settings
    post "/settings/shipping", SettingController, :update_shipping_method_settings

    get "/echo", ChannelEchoController, :echo
    post "/echo", ChannelEchoController, :do_echo


    resources "/option_types", OptionTypeController

    resources "/products", ProductController do
      resources "/variants", VariantController
    end
    resources "/users", UserController
  end

  scope "/api", Nectar.Api do
    pipe_through [:api, :api_auth, Nectar.Plugs.Cart]
    get "/cart", CartController, :show
  end

  use Nectar.RouteExtender
  # Other scopes may use custom stacks.
  # scope "/api", Nectar do
  #   pipe_through :api
  # end
end

apps/nectar/web/controllers/admin/cart_controller.ex
defmodule Nectar.Admin.CartController do
  use Nectar.Web, :admin_controller

  def new(conn, _params) do
    users = Nectar.Repo.all(Nectar.User)
    cart_changeset = Nectar.Order.cart_changeset(%Nectar.Order{}, %{})
    render(conn, "new.html", users: users, cart_changeset: cart_changeset)
  end

  # use guest checkout unless user id provided.
  def create(conn, %{"order" => %{"user_id" => ""}}) do
    order = Nectar.Command.Order.create_empty_cart_for_guest!(Repo)
    conn
    |> redirect(to: admin_cart_path(conn, :edit, order))
  end

  def create(conn, %{"order" => %{"user_id" => user_id}}) do
    order = Nectar.Command.Order.create_empty_cart_for_user!(Repo, user_id)
    conn
    |> redirect(to: admin_cart_path(conn, :edit, order))
  end

  def edit(conn, %{"id" => id}) do
    {:ok, order} = Repo.get!(Nectar.Order, id) |> Nectar.CheckoutManager.back("cart")
    products  =
      Nectar.Query.Product.all(Repo)
      |> Repo.preload([variants: [option_values: :option_type]])

    line_items =
      Nectar.Query.LineItem.in_order(Repo, order)
      |> Repo.preload([variant: [:product, [option_values: :option_type]]])

    render(conn, "edit.html", order: order, products: products, line_items: line_items)
  end

end

apps/nectar/web/controllers/api/cart_controller.ex
defmodule Nectar.Api.CartController do
  use Nectar.Web, :controller

  def show(conn, params) do
    order =
      conn.assigns.current_order
      |> Repo.preload([line_items: [variant: [:product, option_values: :option_type]]])

    render(conn, "cart.json", order: order, summary: Map.get(params, "summary", false), conn: conn)
  end

end

apps/nectar/web/templates/cart/show.html.eex
<%= if cart_empty?(@order) do %>
  <h4>Your cart seems to be empty. Please visit product catalog to add some products to it <%= link "Products", to: product_path(@conn, :index) %></h4>
<% else %>
  <%= form_for @order_changeset, cart_path(@conn, :update), fn f-> %>
  <table class="table" id="cart">
    <thead>
      <tr class="active">
        <th colspan="2">Item</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Total</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody id="line_items">
        <%= inputs_for f, :line_items, fn lf -> %>
          <tr>
            <td colspan="2"><%= lf.data.variant.product.name %><%= Nectar.Admin.VariantView.variant_options_text(lf.data.variant) %></td>
            <td><%= lf.data.variant.cost_price %></td>
            <td><%= number_input lf, :quantity %><%= error_tag lf, :quantity %></td>
            <td><%= lf.data.total %></td>
            <td><%= checkbox lf, :delete %></td>
          </tr>
        <% end %>
      <tr>
        <td colspan="2"><%= submit "Update", class: "btn btn-primary" %></td>
        <td></td>
        <td></td>
        <td><strong>Total</strong></td>
        <td><strong><%= @order.product_total %></strong></td>
      </tr>
    </tbody>
  </table>

<% end %>

  <%= link "Continue Shopping", to: product_path(@conn, :index), class: "btn btn-primary" %>
  <%= link "Goto Checkout", to: checkout_path(@conn, :checkout), class: "btn btn-primary" %>

<% end %>